# Generated by Django 6.0.1 on 2026-04-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_signature_expires_at_signature_signature_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
