# Generated by Django 6.0.1 on 2026-04-19 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_savedsignature'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('oldText', models.TextField(blank=True, null=True)),
                ('newText', models.TextField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_histories', to='api.document')),
            ],
        ),
    ]
