# Generated by Django 6.0.1 on 2026-04-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_documentversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ai_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
