# Generated by Django 5.0 on 2026-05-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_workflowtemplate_workflowtemplatestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='current_step_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='comment_visibility',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
